In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
from scipy.io import wavfile
import librosa
import librosa.display

import pandas as pd
import os
# import sys

from drumbeatid.data.preprocessing import processing_drummers, count_sequences

In [3]:
infocsvfile = '../raw_data/info.csv'
infocsv = pd.read_csv(infocsvfile)

In [7]:
df_drummers = processing_drummers(infocsv)

In [8]:
df_drummers.head()

   bpm beat_type  ...   duration style
0  138      beat  ...  27.872308  funk
1  102      beat  ...  37.691158  soul
2  105      beat  ...  36.351218  funk
3   86      beat  ...  44.716543  soul
4   80      beat  ...  47.987500  soul

[5 rows x 6 columns]

In [9]:
seq=10
df_seq = count_sequences(df_drummers, seq)

In [10]:
df_seq

                   duration  number_sequences
style
gospel           139.527083                13
middleeastern    226.604932                22
blues            288.831759                28
country          299.666435                29
punk             484.656602                48
reggae           619.261933                61
pop              637.575426                63
dance            656.424061                65
afrobeat         796.189359                79
soul            1465.337106               146
neworleans      1519.564186               151
afrocuban       1610.531101               161
hiphop          2025.612826               202
jazz            4115.426525               411
funk            4413.172960               441
latin           6953.082032               695
rock           10718.978988              1071